### PR TITLE
refactor: sdk logger ts typings

### PR DESCRIPTION
**Pull request by eoln**
there was a need to refactor invalid typings

### CODE REVIEW

**Review by lewisdaly — APPROVED** [review]

**Comment by lewisdaly** [comment]
hmm @eoln unit tests are now failing after merging in the latest `master`

**Review by akapur99 — COMMENTED** [review]
lgtm, except the failing unit tests

**Comment by eoln** [comment]
> hmm @eoln unit tests are now failing after merging in the latest `master`

@lewisdaly latest master is broken, so when you merge master into PR it also is broken...

**Review by sridharvoruganti — APPROVED** [review]
lgtm

**Review by elnyry-sam-k — APPROVED** [review]

**Pull request merged**
